"""Auto migration for edited_title

Revision ID: 3e9eb3640d1e
Revises: 54bfc4d9900a
Create Date: 2026-06-24 11:45:38.365163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9eb3640d1e'
down_revision: Union[str, Sequence[str], None] = '54bfc4d9900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_comment="Candidate's expected salary",
               existing_nullable=True)
    op.create_index('ix_applications_candidate_status', 'applications', ['candidate_id', 'status'], unique=False)
    op.create_index('ix_applications_job_id_created_at', 'applications', ['job_id', 'created_at'], unique=False)
    op.create_index('ix_applications_job_id_status', 'applications', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_interview_sessions_expires_at'), 'interview_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_onboarding_documents_application_id'), 'onboarding_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_onboardings_status'), 'onboardings', ['status'], unique=False)
    op.create_index(op.f('ix_onboardings_user_id'), 'onboardings', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('posts', sa.Column('edited_title', sa.Text(), nullable=True, comment='Proposed edited title from team member'))
    op.add_column('posts', sa.Column('edited_description', sa.Text(), nullable=True, comment='Proposed edited description from team member'))
    op.add_column('posts', sa.Column('edited_by_email', sa.String(length=255), nullable=True, comment='Email of team member who submitted the edit'))
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_created_by_status', 'posts', ['created_by', 'status'], unique=False)
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('ix_posts_status_deleted_at', 'posts', ['status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_index('ix_user_integrations_user_platform', 'user_integrations', ['user_id', 'platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_integrations_user_platform', table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index('ix_posts_status_deleted_at', table_name='posts')
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    op.drop_index('ix_posts_created_by_status', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_column('posts', 'edited_by_email')
    op.drop_column('posts', 'edited_description')
    op.drop_column('posts', 'edited_title')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_onboardings_user_id'), table_name='onboardings')
    op.drop_index(op.f('ix_onboardings_status'), table_name='onboardings')
    op.drop_index(op.f('ix_onboarding_documents_application_id'), table_name='onboarding_documents')
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_expires_at'), table_name='interview_sessions')
    op.drop_index('ix_applications_job_id_status', table_name='applications')
    op.drop_index('ix_applications_job_id_created_at', table_name='applications')
    op.drop_index('ix_applications_candidate_status', table_name='applications')
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment="Candidate's expected salary",
               existing_nullable=True)
    # ### end Alembic commands ###
