"""add_attendance

Revision ID: 415d180cf82c
Revises: 8d88f11db4a5
Create Date: 2026-08-21 22:45:54.805484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415d180cf82c'
down_revision: Union[str, Sequence[str], None] = '8d88f11db4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('break_allowed', sa.Boolean(), nullable=False),
    sa.Column('break_max_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_templates_name'), 'shift_templates', ['name'], unique=True)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_break_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'work_date', name='uq_attendance_session_user_work_date')
    )
    op.create_index(op.f('ix_attendance_sessions_shift_id'), 'attendance_sessions', ['shift_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_user_id'), 'attendance_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_work_date'), 'attendance_sessions', ['work_date'], unique=False)
    op.create_table('attendance_breaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('break_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('break_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_breaks_session_id'), 'attendance_breaks', ['session_id'], unique=False)
    op.create_table('employee_shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_profile_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_profile_id', 'effective_from', name='uq_employee_shift_assignment_employee_effective_from')
    )
    op.create_index(op.f('ix_employee_shift_assignments_effective_from'), 'employee_shift_assignments', ['effective_from'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_profile_id'), 'employee_shift_assignments', ['employee_profile_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_shift_id'), 'employee_shift_assignments', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_shift_assignments_shift_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_profile_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_effective_from'), table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    op.drop_index(op.f('ix_attendance_breaks_session_id'), table_name='attendance_breaks')
    op.drop_table('attendance_breaks')
    op.drop_index(op.f('ix_attendance_sessions_work_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_user_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_shift_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_shift_templates_name'), table_name='shift_templates')
    op.drop_table('shift_templates')
    # ### end Alembic commands ###
