"""add_expires_at_to_screening_tests

Revision ID: 42a07c11548f
Revises: beb77fe14c54
Create Date: 2026-07-02 18:27:30.997469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42a07c11548f'
down_revision: Union[str, Sequence[str], None] = 'beb77fe14c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_tests', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_tests', 'expires_at')
    # ### end Alembic commands ###
