"""add_interview_invite_sent_at

Revision ID: 54224e9a59bb
Revises: e2761c4cc2f3
Create Date: 2026-06-24 11:45:05.155250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54224e9a59bb'
down_revision: Union[str, Sequence[str], None] = 'e2761c4cc2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_invite_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last interview invitation sent'))
    op.alter_column('applications', 'interview_invitation_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status of interview invite: NOT_SENT, SENT, DELIVERED, OPENED, RESPONDED, NOT_RESPONDED, DECLINED',
               existing_comment='Status of interview invite: NOT_SENT, SENT, DELIVERED, OPENED, ACCEPTED, DECLINED',
               existing_nullable=True)
    op.create_index(op.f('ix_applications_interview_invite_sent_at'), 'applications', ['interview_invite_sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_interview_invite_sent_at'), table_name='applications')
    op.alter_column('applications', 'interview_invitation_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status of interview invite: NOT_SENT, SENT, DELIVERED, OPENED, ACCEPTED, DECLINED',
               existing_comment='Status of interview invite: NOT_SENT, SENT, DELIVERED, OPENED, RESPONDED, NOT_RESPONDED, DECLINED',
               existing_nullable=True)
    op.drop_column('applications', 'interview_invite_sent_at')
    # ### end Alembic commands ###
