"""auto

Revision ID: 7ba5147cacd9
Revises: 76a2ce00f510
Create Date: 2026-07-08 11:54:33.830581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba5147cacd9'
down_revision: Union[str, Sequence[str], None] = '76a2ce00f510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('idx_job_deadline_history_job_id'), table_name='job_deadline_history')
    op.drop_table('job_deadline_history')
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_comment="Candidate's expected salary",
               existing_nullable=True,
               postgresql_using="NULLIF(regexp_replace(expected_salary, '[^0-9.]', '', 'g'), '')::double precision")
    op.alter_column('applications', 'email_logs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Failure reasons or SMTP logs',
               existing_nullable=True)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_email_delivery_status'), 'applications', ['email_delivery_status'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.alter_column('interview_sessions', 'transcript',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Full chat history',
               existing_nullable=False)
    op.alter_column('interview_sessions', 'state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Internal AI state (current skill, stage, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('interview_sessions', 'programming_language',
               existing_type=sa.VARCHAR(),
               comment='Programming language selected for coding challenge',
               existing_nullable=True,
               existing_server_default=sa.text("'python'::character varying"))
    op.alter_column('interview_sessions', 'recording_url',
               existing_type=sa.VARCHAR(),
               comment='URL/Path to screen recording file',
               existing_nullable=True)
    op.alter_column('interview_sessions', 'recording_path',
               existing_type=sa.VARCHAR(),
               comment='Path to stored screen recording video',
               existing_nullable=True)
    op.alter_column('onboarding_documents', 'file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('onboardings', 'current_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('posts', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_comment='Short summary for social media',
               existing_nullable=True)
    op.alter_column('posts', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_comment='Additional metadata including publications history',
               existing_nullable=True)
    op.drop_constraint(op.f('posts_extended_by_fkey'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'extended_by')
    op.drop_column('posts', 'archived_at')
    op.drop_column('posts', 'extended_at')
    op.drop_column('posts', 'reopened_at')
    op.drop_column('posts', 'closed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('reopened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('extended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('extended_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('posts_extended_by_fkey'), 'posts', 'users', ['extended_by'], ['id'], ondelete='SET NULL')
    op.alter_column('posts', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Additional metadata including publications history',
               existing_nullable=True)
    op.alter_column('posts', 'short_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_comment='Short summary for social media',
               existing_nullable=True)
    op.alter_column('onboardings', 'current_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('onboarding_documents', 'file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('interview_sessions', 'recording_path',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Path to stored screen recording video',
               existing_nullable=True)
    op.alter_column('interview_sessions', 'recording_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL/Path to screen recording file',
               existing_nullable=True)
    op.alter_column('interview_sessions', 'programming_language',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Programming language selected for coding challenge',
               existing_nullable=True,
               existing_server_default=sa.text("'python'::character varying"))
    op.alter_column('interview_sessions', 'state',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Internal AI state (current skill, stage, etc)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('interview_sessions', 'transcript',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Full chat history',
               existing_nullable=False)
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_email_delivery_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.alter_column('applications', 'email_logs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Failure reasons or SMTP logs',
               existing_nullable=True)
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_comment="Candidate's expected salary",
               existing_nullable=True)
    op.create_table('job_deadline_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('new_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('job_deadline_history_changed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['posts.id'], name=op.f('job_deadline_history_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_deadline_history_pkey'))
    )
    op.create_index(op.f('idx_job_deadline_history_job_id'), 'job_deadline_history', ['job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='Job title'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False, comment='Full job description'),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Short summary for social media'),
    sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Job location (city, state, country)'),
    sa.Column('is_remote', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is this a remote position?'),
    sa.Column('location_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='on_site, remote, hybrid'),
    sa.Column('department', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Department or team'),
    sa.Column('salary_min', sa.INTEGER(), autoincrement=False, nullable=True, comment='Minimum salary'),
    sa.Column('salary_max', sa.INTEGER(), autoincrement=False, nullable=True, comment='Maximum salary'),
    sa.Column('salary_currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='Currency code'),
    sa.Column('salary_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='hourly, monthly, yearly'),
    sa.Column('salary_range', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Formatted salary range for display'),
    sa.Column('application_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='URL to apply for the job'),
    sa.Column('application_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email to send applications'),
    sa.Column('application_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Application deadline'),
    sa.Column('required_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='Required skills'),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='Preferred skills'),
    sa.Column('benefits', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='Job benefits'),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'CLOSED', 'ARCHIVED', 'CHANGES_REQUESTED', 'APPROVED', 'EDIT_SUBMITTED', name='jobstatus'), autoincrement=False, nullable=False, comment='Current status'),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When the job was first published'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When the job listing expires'),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Hiring company name'),
    sa.Column('company_logo_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='Company logo URL'),
    sa.Column('company_website', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='Company website'),
    sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='URL-friendly slug'),
    sa.Column('meta_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='SEO meta title'),
    sa.Column('meta_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='SEO meta description'),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='Tags for categorization'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional metadata including publications history'),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of views'),
    sa.Column('application_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of applications'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('jobs_created_by_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    # ### end Alembic commands ###
