"""add_extra_data_to_user_integrations

Revision ID: b9bb5bc4f1ab
Revises: 0ffdecf2d8af
Create Date: 2026-06-29 11:00:01.458309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9bb5bc4f1ab'
down_revision: Union[str, Sequence[str], None] = '0ffdecf2d8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_integrations', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_integrations', 'extra_data')
    # ### end Alembic commands ###
