"""Add interview tracking columns

Revision ID: e2761c4cc2f3
Revises: 2c7953bb244a
Create Date: 2026-06-24 11:07:18.005263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2761c4cc2f3'
down_revision: Union[str, Sequence[str], None] = '2c7953bb244a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_invitation_status', sa.String(length=50), nullable=True, comment='Status of interview invite: NOT_SENT, SENT, DELIVERED, OPENED, ACCEPTED, DECLINED'))
    op.add_column('applications', sa.Column('last_interview_invite_id', sa.String(length=255), nullable=True, comment='Resend message ID for the last interview invite'))
    op.alter_column('applications', 'source',
               existing_type=sa.VARCHAR(),
               comment='Source: web, linkedin, indeed, agent, etc.',
               existing_nullable=True)
    op.alter_column('applications', 'city',
               existing_type=sa.VARCHAR(),
               comment="Candidate's city",
               existing_nullable=True)
    op.alter_column('applications', 'qualification',
               existing_type=sa.VARCHAR(),
               comment='Highest qualification',
               existing_nullable=True)
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               comment="Candidate's expected salary",
               existing_nullable=True)
    op.alter_column('applications', 'salary_filter_status',
               existing_type=sa.VARCHAR(),
               comment='within_budget | above_budget | not_checked',
               existing_nullable=True)
    op.alter_column('applications', 'email_delivery_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Email status: PENDING, SENT, FAILED, SKIPPED',
               existing_comment='Email status: PENDING, SENT, FAILED',
               existing_nullable=True)
    op.alter_column('applications', 'email_logs',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using='to_json(email_logs)',
               existing_comment='Failure reasons or SMTP logs',
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.drop_index(op.f('ix_applications_job_id_created_at'), table_name='applications')
    op.create_index('ix_applications_job_id_created_at', 'applications', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_applications_interview_invitation_status'), 'applications', ['interview_invitation_status'], unique=False)
    op.create_index(op.f('ix_applications_last_interview_invite_id'), 'applications', ['last_interview_invite_id'], unique=False)
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    op.drop_constraint(op.f('onboardings_onboarding_token_key'), 'onboardings', type_='unique')
    op.drop_index(op.f('ix_onboardings_onboarding_token'), table_name='onboardings')
    op.create_index(op.f('ix_onboardings_onboarding_token'), 'onboardings', ['onboarding_token'], unique=True)
    op.alter_column('posts', 'required_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Required skills',
               existing_nullable=True)
    op.alter_column('posts', 'preferred_skills',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Preferred skills',
               existing_nullable=True)
    op.alter_column('posts', 'requirements',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Mandatory requirements/qualifications',
               existing_nullable=True)
    op.alter_column('posts', 'preferred_qualifications',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Preferred qualifications',
               existing_nullable=True)
    op.alter_column('posts', 'benefits',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Job benefits',
               existing_nullable=True)
    op.alter_column('posts', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Tags for categorization',
               existing_nullable=True)
    op.alter_column('posts', 'manager_feedback',
               existing_type=sa.TEXT(),
               comment='Feedback from Operation Manager',
               existing_comment='Internal feedback from hiring manager',
               existing_nullable=True)
    op.alter_column('posts', 'edited_title',
               existing_type=sa.TEXT(),
               comment='Proposed edited title from team member',
               existing_nullable=True)
    op.alter_column('posts', 'edited_description',
               existing_type=sa.TEXT(),
               comment='Proposed edited description from team member',
               existing_nullable=True)
    op.alter_column('posts', 'edited_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email of team member who submitted the edit',
               existing_nullable=True)
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_posts_status_created_at'), table_name='posts')
    op.create_index('ix_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_expires_at'), 'posts', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_expires_at'), table_name='posts')
    op.drop_index('ix_posts_status_created_at', table_name='posts')
    op.create_index(op.f('ix_posts_status_created_at'), 'posts', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.create_index(op.f('ix_posts_created_at'), 'posts', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('posts', 'edited_by_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email of team member who submitted the edit',
               existing_nullable=True)
    op.alter_column('posts', 'edited_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Proposed edited description from team member',
               existing_nullable=True)
    op.alter_column('posts', 'edited_title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Proposed edited title from team member',
               existing_nullable=True)
    op.alter_column('posts', 'manager_feedback',
               existing_type=sa.TEXT(),
               comment='Internal feedback from hiring manager',
               existing_comment='Feedback from Operation Manager',
               existing_nullable=True)
    op.alter_column('posts', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Tags for categorization',
               existing_nullable=True)
    op.alter_column('posts', 'benefits',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Job benefits',
               existing_nullable=True)
    op.alter_column('posts', 'preferred_qualifications',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Preferred qualifications',
               existing_nullable=True)
    op.alter_column('posts', 'requirements',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Mandatory requirements/qualifications',
               existing_nullable=True)
    op.alter_column('posts', 'preferred_skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Preferred skills',
               existing_nullable=True)
    op.alter_column('posts', 'required_skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Required skills',
               existing_nullable=True)
    op.drop_index(op.f('ix_onboardings_onboarding_token'), table_name='onboardings')
    op.create_index(op.f('ix_onboardings_onboarding_token'), 'onboardings', ['onboarding_token'], unique=False)
    op.create_unique_constraint(op.f('onboardings_onboarding_token_key'), 'onboardings', ['onboarding_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_last_interview_invite_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_interview_invitation_status'), table_name='applications')
    op.drop_index('ix_applications_job_id_created_at', table_name='applications')
    op.create_index(op.f('ix_applications_job_id_created_at'), 'applications', ['job_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.create_index(op.f('ix_applications_created_at'), 'applications', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('applications', 'email_logs',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_comment='Failure reasons or SMTP logs',
               existing_nullable=True)
    op.alter_column('applications', 'email_delivery_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Email status: PENDING, SENT, FAILED',
               existing_comment='Email status: PENDING, SENT, FAILED, SKIPPED',
               existing_nullable=True)
    op.alter_column('applications', 'salary_filter_status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='within_budget | above_budget | not_checked',
               existing_nullable=True)
    op.alter_column('applications', 'expected_salary',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               comment=None,
               existing_comment="Candidate's expected salary",
               existing_nullable=True)
    op.alter_column('applications', 'qualification',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Highest qualification',
               existing_nullable=True)
    op.alter_column('applications', 'city',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Candidate's city",
               existing_nullable=True)
    op.alter_column('applications', 'source',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Source: web, linkedin, indeed, agent, etc.',
               existing_nullable=True)
    op.drop_column('applications', 'last_interview_invite_id')
    op.drop_column('applications', 'interview_invitation_status')
    # ### end Alembic commands ###
